# Generated by Django 4.2.3 on 2024-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
