# Generated by Django 5.1.2 on 2024-10-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
