# Generated by Django 5.1.2 on 2024-10-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent_id',
            new_name='payment_id',
        ),
    ]
